import type { selfBookingRules } from "@/db/schema";

export type NormalizedCalendarEvent = {
  googleEventId: string;
  title: string;
  description?: string | null;
  start: Date;
  end: Date;
  attendees: { email: string; name?: string | null }[];
  organizerEmail?: string | null;
  meetingLink?: string | null;
  location?: string | null;
  isCancelled: boolean;
  updatedAt: Date;
  calendarSourceLabel?: string | null;
  /** Marcador de cor do evento no Google Calendar (colorId da API, "1"-"11"). */
  colorId?: string | null;
};

/**
 * Extrai um telefone do texto livre da descrição do evento. O formulário de
 * Self Booking grava os dados do lead na descrição do evento (padrão
 * "Telefone: +55 11 91234-5678"); quando não há rótulo explícito, cai para
 * qualquer sequência que pareça um telefone brasileiro (com ou sem DDI/DDD).
 */
export function extractPhoneFromDescription(description?: string | null): string | null {
  if (!description) return null;

  const labeled = description.match(/(?:telefone|tel|celular|whatsapp|phone)\s*:?\s*([+()\d][\d\s()/.-]{7,}\d)/i);
  if (labeled) return labeled[1].trim();

  const generic = description.match(/(\+?\d{1,3}[\s.-]?)?\(?\d{2}\)?[\s.-]?9?\d{4}[\s.-]?\d{4}/);
  return generic ? generic[0].trim() : null;
}

type Rule = typeof selfBookingRules.$inferSelect;

// Prefixos usados pelos SDRs para identificar reuniões que ELES agendaram
// manualmente (não são Self Booking do lead). Ex: "SA | João e Felipe Paiva",
// "SL | Marcéllio e Vitor Moura". Checagem case-insensitive.
const SDR_BOOKING_PREFIXES = ["SA", "SL"];

// Closers conhecidos hoje, do jeito que o nome aparece no título dos eventos
// ("<cliente> e <closer>"). Ao contratar um novo closer, adicione o nome
// aqui — ou simplesmente nomeie a agenda monitorada em Configurações →
// Integrações com esse mesmo nome (ex: "Maria" ou "Maria - Closer"), que o
// sistema já reconhece automaticamente pelo rótulo da agenda de origem.
export const KNOWN_CLOSER_NAMES = ["Felipe Paiva", "Vitor Moura"];

function hasSdrBookingPrefix(title: string): boolean {
  const t = title.trim().toUpperCase();
  return SDR_BOOKING_PREFIXES.some(
    (p) => t.startsWith(`${p} `) || t.startsWith(`${p}|`) || t.startsWith(`${p} |`)
  );
}

function closerNamesForEvent(event: NormalizedCalendarEvent): string[] {
  const names = [...KNOWN_CLOSER_NAMES];
  if (event.calendarSourceLabel) {
    // "Felipe Paiva - Closer" -> "Felipe Paiva"
    const fromLabel = event.calendarSourceLabel.split(/[-|]/)[0].trim();
    if (fromLabel) names.push(fromLabel);
  }
  return names;
}

/** Título no padrão "<cliente> e <closer>", sem prefixo de agendamento do SDR. */
function matchesCloserPattern(event: NormalizedCalendarEvent): boolean {
  const title = event.title.toLowerCase();
  return closerNamesForEvent(event).some((name) =>
    title.includes(` e ${name.toLowerCase()}`)
  );
}

/**
 * Extrai o nome do cliente a partir do título do evento, no padrão
 * "<cliente> e <closer>" (ex: "Ana Souza e Felipe Paiva" -> "Ana Souza").
 * É a fonte mais confiável de nome completo: o participante do Google
 * Calendar quase nunca tem "nome de exibição" preenchido (só e-mail), mas o
 * título do evento é digitado pelo próprio lead no formulário de Self
 * Booking. Retorna null se o título não seguir o padrão esperado.
 */
export function extractClientNameFromTitle(event: NormalizedCalendarEvent): string | null {
  const title = event.title.trim();
  const titleLower = title.toLowerCase();
  for (const name of closerNamesForEvent(event)) {
    const marker = ` e ${name.toLowerCase()}`;
    const idx = titleLower.indexOf(marker);
    if (idx > 0) {
      const client = title.slice(0, idx).trim().replace(/^(sa|sl)\s*[|]?\s*/i, "").trim();
      if (client) return client;
    }
  }
  return null;
}

/**
 * Extrai um nome a partir de um rótulo explícito na descrição do evento
 * (ex: "Nome: Ana Souza"), quando o formulário grava esse dado ali.
 */
export function extractNameFromDescription(description?: string | null): string | null {
  if (!description) return null;
  // ":" é obrigatório aqui para não confundir com o rótulo fixo "Nome do
  // evento" que o formulário grava na primeira linha da descrição (esse não
  // tem ":", então não bate com o padrão abaixo).
  const labeled = description.match(/(?:nome completo|nome do cliente|nome|cliente)\s*:\s*([^\n\r]{2,80})/i);
  return labeled ? labeled[1].trim() : null;
}

/**
 * Detecta um nome "gerado automaticamente" (sem nome de exibição disponível,
 * o sistema usou o prefixo do e-mail como nome — ex: "joao.silva123" a
 * partir de "joao.silva123@gmail.com"). Usado para saber quando vale a pena
 * tentar corrigir o nome de um lead já cadastrado.
 */
export function looksAutoGeneratedLeadName(name: string, email?: string | null): boolean {
  if (!email) return false;
  const localPart = email.split("@")[0]?.toLowerCase();
  return Boolean(localPart) && name.trim().toLowerCase() === localPart;
}

/**
 * Decide se um evento do Google Calendar deve ser tratado como Self Booking.
 * Não depende só do título: considera calendário de origem, palavras-chave,
 * padrão de e-mail do participante e responsável configurados em
 * Configurações → Regras de Self Booking.
 *
 * Eventos com prefixo "SA"/"SL" no título são sempre agendamentos feitos
 * pelo próprio SDR (não Self Booking), independente de outras regras.
 *
 * Se não houver nenhuma regra ativa cadastrada, usa o padrão
 * "<cliente> e <closer>" no título para diferenciar Self Booking de outras
 * reuniões (onboarding, treinamento etc.) que também aparecem na mesma
 * agenda monitorada.
 */
export function matchesSelfBookingRules(
  event: NormalizedCalendarEvent,
  calendarSourceId: string | null,
  rules: Rule[]
): boolean {
  if (hasSdrBookingPrefix(event.title)) return false;

  const activeRules = rules.filter((r) => r.active);
  if (activeRules.length === 0) return matchesCloserPattern(event);

  const applicable = activeRules.filter(
    (r) => !r.calendarSourceId || r.calendarSourceId === calendarSourceId
  );
  if (applicable.length === 0) return matchesCloserPattern(event);

  return applicable.some((rule) => ruleMatches(event, rule));
}

function ruleMatches(event: NormalizedCalendarEvent, rule: Rule): boolean {
  let matched = true;

  if (rule.titleKeywords) {
    const keywords = rule.titleKeywords
      .split(",")
      .map((k) => k.trim().toLowerCase())
      .filter(Boolean);
    if (keywords.length > 0) {
      const title = event.title.toLowerCase();
      matched = matched && keywords.some((k) => title.includes(k));
    }
  }

  if (rule.attendeeEmailPattern) {
    const pattern = rule.attendeeEmailPattern.trim();
    if (pattern && pattern !== "*" && pattern !== "*@*") {
      const domain = pattern.replace("*@", "").toLowerCase();
      matched =
        matched &&
        event.attendees.some((a) => a.email.toLowerCase().endsWith(domain));
    }
  }

  return matched;
}

/** Identifica o participante externo (o lead) dentre os attendees do evento. */
export function extractLeadAttendee(
  event: NormalizedCalendarEvent,
  internalDomains: string[]
): { email: string; name?: string | null } | null {
  const external = event.attendees.filter(
    (a) =>
      !internalDomains.some((d) => a.email.toLowerCase().endsWith(d.toLowerCase())) &&
      a.email.toLowerCase() !== (event.organizerEmail ?? "").toLowerCase()
  );
  return external[0] ?? event.attendees[0] ?? null;
}
