"use server";

import { revalidatePath } from "next/cache";
import { eq, desc, inArray } from "drizzle-orm";
import { db } from "@/db";
import { leads, meetings, calendarSources } from "@/db/schema";
import { requireRole, requireUser } from "@/lib/auth";
import { logAudit } from "@/lib/audit";
import {
  extractClientNameFromTitle,
  extractPhoneFromDescription,
  looksAutoGeneratedLeadName,
} from "@/lib/self-booking-rules";
import { isInternalEmail } from "@/lib/ingest";

export async function updateLeadAction(leadId: string, formData: FormData) {
  const user = await requireUser();
  const [before] = await db.select().from(leads).where(eq(leads.id, leadId)).limit(1);
  if (!before) throw new Error("Lead não encontrado");
  if (user.role === "sdr" && before.sdrUserId !== user.id) {
    throw new Error("Sem permissão para editar este lead");
  }

  const patch = {
    name: String(formData.get("name") || before.name),
    company: (formData.get("company") as string) || null,
    email: (formData.get("email") as string) || null,
    phone: (formData.get("phone") as string) || null,
    whatsapp: (formData.get("whatsapp") as string) || null,
    role: (formData.get("role") as string) || null,
    updatedAt: new Date(),
  };

  await db.update(leads).set(patch).where(eq(leads.id, leadId));
  await logAudit({
    userId: user.id,
    action: "lead_atualizado",
    entityType: "lead",
    entityId: leadId,
    before,
    after: patch,
  });
  revalidatePath("/", "layout");
}

/**
 * Corrige, de uma vez, os leads cujo nome ficou igual ao prefixo do e-mail
 * (sincronizados antes de sabermos extrair o nome do título do evento), lendo
 * o título bruto ("<cliente> e <closer>") da reunião mais recente de cada um.
 * Não altera nomes editados manualmente. Retorna quantos foram corrigidos.
 */
export async function backfillLeadNamesAction() {
  const admin = await requireRole(["admin", "coordinator"]);

  const allLeads = await db.select().from(leads);
  const candidates = allLeads.filter((l) => looksAutoGeneratedLeadName(l.name, l.email));

  let corrigidos = 0;
  for (const lead of candidates) {
    const [latestMeeting] = await db
      .select({ meeting: meetings, calendarLabel: calendarSources.label })
      .from(meetings)
      .leftJoin(calendarSources, eq(meetings.calendarSourceId, calendarSources.id))
      .where(eq(meetings.leadId, lead.id))
      .orderBy(desc(meetings.createdAt))
      .limit(1);
    if (!latestMeeting?.meeting.rawTitle) continue;

    const newName = extractClientNameFromTitle({
      googleEventId: "",
      title: latestMeeting.meeting.rawTitle,
      start: latestMeeting.meeting.scheduledAt,
      end: latestMeeting.meeting.scheduledAt,
      attendees: [],
      isCancelled: false,
      updatedAt: new Date(),
      calendarSourceLabel: latestMeeting.calendarLabel,
    });
    const newPhone = !lead.phone ? extractPhoneFromDescription(latestMeeting.meeting.rawDescription) : null;

    if ((newName && newName.toLowerCase() !== lead.name.toLowerCase()) || newPhone) {
      await db
        .update(leads)
        .set({
          ...(newName ? { name: newName } : {}),
          ...(newPhone ? { phone: newPhone } : {}),
          updatedAt: new Date(),
        })
        .where(eq(leads.id, lead.id));
      corrigidos++;
    }
  }

  await logAudit({
    userId: admin.id,
    action: "leads_nomes_corrigidos_em_lote",
    entityType: "lead",
    after: { totalCandidatos: candidates.length, corrigidos },
  });
  revalidatePath("/", "layout");
  return { totalCandidatos: candidates.length, corrigidos };
}

/**
 * Remove leads que na verdade são pessoas de dentro do grupo.
 *
 * Eventos agendados por outros sistemas (SDR Hub) colocam um e-mail interno
 * como convidado e deixam o nome do lead só no título. Enquanto
 * nexaeducacao.com não estava na lista de domínios internos, a sincronização
 * lia esse e-mail como se fosse um lead e ia empilhando reuniões de pessoas
 * diferentes num único cadastro (o caso do lead "Frederico").
 *
 * A sincronização já não cria mais esses registros — esta ação limpa os que
 * ficaram para trás. Apagar o lead leva junto, em cascata, as reuniões,
 * tarefas e interações penduradas nele, que também eram inválidas.
 */
export async function cleanupInternalLeadsAction() {
  const user = await requireRole(["admin", "coordinator"]);

  const withEmail = await db
    .select({ id: leads.id, name: leads.name, email: leads.email })
    .from(leads);

  const internos = withEmail.filter((l) => l.email && isInternalEmail(l.email));
  if (internos.length === 0) return { removidos: 0, nomes: [] as string[] };

  await db.delete(leads).where(
    inArray(
      leads.id,
      internos.map((l) => l.id)
    )
  );

  await logAudit({
    userId: user.id,
    action: "leads_internos_removidos",
    entityType: "lead",
    after: { total: internos.length, leads: internos },
  });

  revalidatePath("/", "layout");
  return { removidos: internos.length, nomes: internos.map((l) => l.name) };
}
